spring:
  application:
    name: service-registry
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      fail-fast: true
server:
  port: 8761
eureka:
  instance:
    hostname: "${HOSTNAME:localhost}.eureka"
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS}
