spring:
  config:
    import:
      configserver:
  application:
    name: api-gateway
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOriginPatterns:
              - "*"
            allowCredentials: true
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: question-service
          uri:
            lb://question-service
          predicates:
            - Path=/question/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: question-service
#                fallbackuri: forward:/questionServiceFallBack

        - id: quiz-service
          uri:
            lb://quiz-service
          predicates:
            - Path=/quiz/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: quiz-service
#                fallbackuri: forward:/quizServiceFallBack
        - id: contribute-service
          uri:
            lb://contribute-service
          predicates:
            - Path=/contribute/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: contribute-service
#                fallbackuri: forward:/contributeServiceFallBack

#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMillseconds:  4000

#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local.8761/eureka
       defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
