apiVersion: v1
kind: Pod
metadata:
  name: my-ubuntu-app
spec:
  containers:
  - name: my-ubuntu-container
    image: ubuntu:latest
    command: ["sleep", "infinity"]
    env:
    - name: DB_URL
      value: jdbc:mysql://localhost:3306/Question?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=TRUE
    - name: DB_USERNAME
      value: root
    - name: DB_PASSWORD
      value: Hemanth@2000
    - name: EUREKA_BOO
      value: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
