apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service-app
  labels:
    app: question-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-service-app
  template:
    metadata:
      labels:
        app: question-service-app
    spec:
      containers:
        - name: question-service-app
          image: saihemanth1997/question-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: mysql-svc
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: Question
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: Hemanth@2000
---
apiVersion: v1
kind: Service
metadata:
  name: question-service-app
spec:
  selector:
    app: question-service-app
  ports:
    - port: 80
      targetPort: 8080
