apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service-app
  labels:
    app: question-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question-service-app
  template:
    metadata:
      labels:
        app: question-service-app
    spec:
      containers:
        - name: question-service-app
          image: saihemanth1997/question-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              value: jdbc:mysql://mysql-svc:3306/Question?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=TRUE
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: Hemanth@2000
---
apiVersion: v1
kind: Service
metadata:
  name: question-service-app
spec:
  # type: NodePort
  selector:
    app: question-service-app
  ports:
    - port: 80
      targetPort: 8080
