management:
  tracing:
    sampling:
      probability: 1.0
spring:
  application:
    name: quiz-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/Quiz?createDatabaseIfNotExist=true
    username: root
    password: Hemanth@2000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8090
eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local.8761/eureka
       defaultZone: http://localhost:8761/eureka/


