name: Microservices CI/CD Pipeline

env:
  MYSQL_DATABASE: Question
  MYSQL_ROOT_PASSWORD: Billa@258
  MYSQL_HOST: localhost

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_HOST: ${{ env.MYSQL_HOST }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"

      - name: Wait for MySQL to be ready
        run: dockerize -wait tcp://localhost:3306 -timeout 1m

      - name: Secure MySQL root password
        run: mysql -h localhost -u root -p"${{ env.MYSQL_ROOT_PASSWORD }}" --execute="ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '${{ env.MYSQL_ROOT_PASSWORD }}';"

      - name: Building and Pushing Question Service
        run: |
          mvn package dockerfile:push --file question-service/pom.xml \
          -Dspring.datasource.url=jdbc:mysql://${{ env.MYSQL_HOST }}:3306/${{ env.MYSQL_DATABASE }} \
          -Dspring.datasource.username=root \
          -Dspring.datasource.password=${{ env.MYSQL_ROOT_PASSWORD }}
        env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
