# documentation.

name: Microservices CI/CD Pipeline
on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          server-id: docker.io
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          distribution: "temurin"
          cache: maven

  #     - name: Building and Pushing Question Service
  # run: mvn package dockerfile:push --file question-service/pom.xml
  # env:
  #   MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #   MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  # services:
  #   mysql:
  #     image: mysql:latest
  #     env:
  #       MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
  #       MYSQL_DATABASE: your_database_name
  #       MYSQL_USER: your_database_user
  #       MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
  #     ports:
  #       - 3306:3306
      - name: Building and Pushing Question Service
        run : mvn package dockerfile:push --file question-service/pom.xml
        env :
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME}}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
        services:
           mysql: 
            image: mysql:latest
            env:
             MYSQL_ROOT_PASSWORD: Billa@258
             MYSQL_DATABASE: Question
             MYSQL_USER: root
             MYSQL_PASSWORD: Billa@258
            ports:
             - 3306:3306

      - name: Building and Pushing Quiz Service
        run: mvn  package dockerfile:push --file quiz-service/pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Building and Pushing Contribute Service
        run: mvn  package dockerfile:push --file contribute-service/pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Building and Pushing Config server
        run: mvn  package dockerfile:push --file cloud-config-server/pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Building and Pushing Server registry
        run: mvn  package dockerfile:push --file service-registry/pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Building and Pushing Api gateway
        run: mvn  package dockerfile:push --file api-gateway/pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
